apiVersion: v1
kind: Secret
metadata:
  name: gcrf-db-secret
  namespace: gcrf-prod
type: Opaque
stringData:
  POSTGRES_HOST: postgresql.edu-infra.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "EduPlatform2026!"
  REDIS_HOST: redis.edu-infra.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "EduRedis2026!"
  JWT_SECRET: "gcrf-library-jwt-secret-2026-production-key-must-be-64-chars-long!"
